[[redirects]]
  from = "https://alexmg.com/posts/*"
  to = "https://alexmg.dev/posts/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://alexmg.com/*"
  to = "https://alexmg.dev/posts/:splat"
  status = 301
  force = true