name: Build and deploy to Netlify

on:
  push:
    branches:
      - master
    paths:
      - '*'
      - '!/drafts/*'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.401

      - name: Build and deploy
        env:
          NETLIFY_TOKEN: ${{ secrets.NetlifyToken }}
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
          NUGET_XMLDOC_MODE: skip
        run: build -target BuildServer