name: Build and deploy to Netlify

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - /drafts/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302

    - name: Deploy
      env:
        NETLIFY_TOKEN: ${{ secrets.NETLIFYTOKEN }}
      run: dotnet run -- deploy