name: Build and deploy to Netlify

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - /drafts/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Deploy
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFYTOKEN }}
        run: dotnet run -- deploy
